version: 2.1
executors:
  default:
    docker:
      - image: cimg/base:2021.10
orbs:
  node: circleci/node@5.0.0
  heroku: circleci/heroku@1.1.1 # Add Heroku orb
jobs:
  build-and-test:
    docker:
      - image: cimg/ruby:3.2.2
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: weather_together_be_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run:
          name: Force Bundler Version
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:{create,migrate} --trace
      - run:
          name: Run rspec in parallel
          command: bundle exec rspec
      - store_test_results:
          path: test_results
  deploy:
    executor: default
    steps:
      - checkout
      - setup_remote_docker: # Required to use the heroku orb
          version: 20.10.7
      - heroku/install
      - heroku/deploy-via-git: # Deploy to Heroku via git
          app-name: powerful-sierra-25067 
workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main